#!/bin/sh
function build() {
    deno run build;
}

function link() {

    BASE=$(dirname $(realpath $0))

    EXE_LINK=$HOME/.deno/bin/rpcdev
    EXE_FILE=$BASE/rpcdev

    chmod +x $EXE_FILE

    if [ -L $EXE_LINK ]; then rm $EXE_LINK; fi

    ln -s $EXE_FILE $EXE_LINK;

    echo "Installed at: $EXE_LINK"
    echo "Linked from: $EXE_FILE"
}

build;
link;
rpcdev;